# Site settings
title: Universal Split Screen
email: ilyaki@protonmail.com
description: >
  Split screen multiplayer for any game with multiple keyboards, mice and controllers.
lang: en-US
encoding: UTF-8

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://universalsplitscreen.github.io/ # the base hostname & protocol for your site
git_address: https://github.com/UniversalSplitScreen/UniversalSplitScreen
#git_edit_address: https://github.com/UniversalSplitScreen/UniversalSplitScreen.github.io/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
#bootwatch: paper
bootwatch: Flatly

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/London
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
